runtime: go119
env: standard
instance_class: B1
basic_scaling:
  idle_timeout: 300s
  max_instances: 1

handlers:
  - url: /(.*\.(html|css))$
    static_files: static/\1
    upload: static/.*\.(html|css)$

  - url: /.*
    script: auto
