runtime: python39
instance_class: B1
service: default
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
  - url: /(.*\.css)
    mime_type: text/css
    static_files: static/\1
    upload: static/(.*\.css)

  # site root
  - url: /
    static_files: static/index.html
    upload: static/index.html
    expiration: "15m"
