# This is a basic workflow to help you get started with Actions
name: Deploy to Google App Engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud App Engine 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud 🔑
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Setting up gcloud CLI 🔧
        # Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1.0.1
        with:
          version: "412.0.0"
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Deploy an App Engine app 🚀
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          deliverables: app.yaml
          version: v1
          working_directory: .

      # use the output
      - name: Test the deployed app 🧪
        id: "Test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
